export const ACTIONS = {
  DECREASE: "DECREASE",
  INCREASE: "INCREASE",
  REMOVE: "REMOVE",
  CLEAR_CART: "CLEAR_CART",
  GET_TOTAL: "GET_TOTAL",
  TOGGLE_AMOUNT: "TOGGLE_AMOUNT",
  // GET_AMOUNT: "GET_AMOUNT",
};